### PR TITLE
corrected prolongation and restriction operator on first and last circles

### PR DESCRIPTION
**Pull request by mknaranja**
## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
Always to be checked:
* [x] There is at least one issue associated with the pull request.
* [x] New code adheres with the [coding guidelines](https://github.com/mknaranja/GMGPolar/wiki)
* [x] No large data files have been added to the repository. Maximum size for files should be of the order of KB not MB. In particular avoid adding of pdf, word, or other files that cannot be change-tracked correctly by git.

If functions were changed or functionality was added:
* [ ] Tests for new functionality has been added
* [ ] A local test was succesful

If new functionality was added:
* [ ] There is appropriate **documentation** of your work. (use doxygen style comments)

If new third party software is used:
* [ ] Did you pay attention to its license? Please remember to add it to the wiki after successful merging.

If new mathematical methods or epidemiological terms are used:
* [ ] Are new methods referenced? Did you provide further documentation?

[ ] The following questions are addressed in the documentation (if need be): 
* Developers (what did you do?, how can it be maintained?)
* For users (how to use your work?)
* For admins (how to install and configure your work?)

* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [x] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [x] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [x] The git history is clean and linearized for the merge request. All reviewers should squash commits and write a simple and meaningful commit message.
* [ ] Coverage report for new code is acceptable. 
* [x] No large data files have been added to the repository. Maximum size for files should be of the order of KB not MB. In particular avoid adding of pdf, word, or other files that cannot be change-tracked correctly by git.

### CODE REVIEW

**Comment by mknaranja** [comment]
It seems this gives error with --matrix-free=0 and small grid sizes like 33x64 points. Should be checked. If you find the time, could you do so @CodingAllan ?

**Comment by CodingAllan** [comment]
I have tried to run my own tests to see where the problem lie. In the test for apply_prolongation_ex() I get a memory error. 
At first I couldnt find any problems with the implementation. 
But then I tried to remove the parallel OpenMP commands and see if the program runs without problems sequentially. And surprisingly it does. So I guess something is not working there. Sadly I dont know anything about OpenMP.

There are some problems regarding the build_prolongation function for matrix dependent applications.. But maybe that got resolved already!

@mknaranja

**Review by chrissy-s96 — APPROVED** [review]

**Comment by mknaranja** [comment]
@carolakruse Could you approve the changes?

**Review by carolakruse — APPROVED** [review]
Looks good to me!

**Pull request merged**
